package:
  name: minecraft-bds
  version: 1.20.0.21
  description: Minecraft Bedrock Dedicated Server
  # target-architecture:
  #   - all
  # copyright:
  #   - license: Apache-2.0
  #     paths:
  #       - "*"

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - ca-certificates-bundle
      - curl

pipeline:
  - name: Install itzg/set-property
    uses: go/install
    with:
      package: github.com/itzg/set-property
      version: 0.1.1

  - name: Fetch BDS zip
    uses: fetch
    with:
      uri: https://minecraft.azureedge.net/bin-linux-preview/bedrock-server-${{package.version}}.zip
      extract: false
      expected-sha256: 62cabb47d59b32f7da90be694eff58eee05103a5cc4b77ba20ae1a0cee3be461
      
  - name: Unzip BDS zip
    runs: |
      unzip bedrock-server-${{package.version}}.zip
      rm bedrock-server-${{package.version}}.zip bedrock_server_* release-notes.txt
