name: Build OCI image v2
run-name: Build Image [${{ inputs.BDS_VERSION }}]
on:
  workflow_dispatch:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: chainguard-dev/actions/melange-build@main
        with:
          empty-workspace: true
