name: Build OCI image
run-name: Build Image [${{ inputs.BDS_VERSION }}]
on:
  workflow_dispatch:
    inputs:
      BDS_VERSION:
        description: "The BDS version"
        default: "1.19.30.04"
        required: true
        type: string
      USE_STABLE_TAG:
        description: "Attach the stable tag to image"
        default: false
        required: true
        type: boolean
      USE_PREVIEW_TAG:
        description: "Attach the preview tag to image"
        default: false
        required: true
        type: boolean
      USE_LATEST_TAG:
        description: "Attach the latest tag to image"
        default: false
        required: true
        type: boolean

      DUMP_DEFAULTS:
        description: "Dump default files as part of pipeline"
        default: false
        required: true
        type: boolean

env:
  IMAGE_NAME: bedrock-server
  IMAGE_REGISTRY: ghcr.io/scriptapioss
  REGISTRY_USER: ${{ github.repository_owner }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  LATEST_TAG: ""
jobs:
  defaults:
    name: Dump defaults
    if: inputs.DUMP_DEFAULTS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Attach preview tag
        if: inputs.USE_PREVIEW_TAG
        run: |
          echo "PATH_MODIFIER=_preview" >> $GITHUB_ENV

      - name: Download and dump
        run: |
          mkdir dump/
          rm -rf defaults/
          mkdir defaults/

          BDS_URL=`curl -s https://raw.githubusercontent.com/ScriptAPIOSS/BDS-Versions/main/linux${{ env.PATH_MODIFIER }}/${{ inputs.BDS_VERSION }}.json | jq -r '.download_url'` && wget -q ${BDS_URL} -O dump/bds.zip
          cd dump/
          unzip bds.zip

          mv config/ ../defaults/config/
          mv server.properties ../defaults/server.properties

          cd ..

          rm -rf dump/

      - name: Check if there is any change
        id: changes
        run: echo "changed=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.changes.outputs.changed != 0
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update defaults for ${{ inputs.BDS_VERSION }}
          title: New defaults for ${{ inputs.BDS_VERSION }}
          body: New changes were discovered for ${{ inputs.BDS_VERSION }}, please review
          labels: defaults
          assignees: GTB3NW
          reviewers: GTB3NW
          branch: defaults-${{ inputs.BDS_VERSION }}
          base: main

  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Sermver tags
        run: |
          VERSION="${{ inputs.BDS_VERSION }}"
          VERSION="${VERSION#[vV]}"
          VERSION_MAJOR="${VERSION%%\.*}"
          VERSION_MINOR="${VERSION#*.}"
          VERSION_MINOR="${VERSION_MINOR%.*}"
          VERSION_PATCH="${VERSION##*.}"

          echo "MAJORMINORVERSION=latest-${VERSION_MAJOR}.${VERSION_MINOR}" >> $GITHUB_ENV

      - name: Attach latest tag
        if: inputs.USE_LATEST_TAG
        run: echo "LATEST_TAG=latest" >> $GITHUB_ENV
      - name: Attach stable tag
        if: inputs.USE_STABLE_TAG
        run: |
          echo "STABLE_TAG=stable" >> $GITHUB_ENV
          echo "PATH_MODIFIER=" >> $GITHUB_ENV
      - name: Attach preview tag
        if: inputs.USE_PREVIEW_TAG
        run: |
          echo "PREVIEW_TAG=preview" >> $GITHUB_ENV
          echo "PATH_MODIFIER=_preview" >> $GITHUB_ENV

      - name:
        run: |
          BDS_CHANGELOG=`curl -s https://raw.githubusercontent.com/ScriptAPIOSS/BDS-Versions/main/release_notes/linux${{ env.PATH_MODIFIER }}/${{ inputs.BDS_VERSION }}.txt`
          # echo "BDS_CHANGELOG=${BDS_CHANGELOG}" >> $GITHUB_ENV

      - name: Buildah Action
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.MAJORMINORVERSION }} ${{ env.LATEST_TAG }} ${{ env.STABLE_TAG }} ${{ env.PREVIEW_TAG }} ${{ inputs.BDS_VERSION }}
          containerfiles: |
            ./Containerfile
          build-args: |
            BDS_VERSION=${{ inputs.BDS_VERSION }}
            PATH_MODIFIER=${{ env.PATH_MODIFIER }}
          labels: |
            org.opencontainers.image.title=Minecraft Bedrock Dedicated Server
            # org.opencontainers.image.description=${{ env.BDS_CHANGELOG }}
            org.opencontainers.image.version=${{ inputs.BDS_VERSION }}
            org.opencontainers.image.licenses=https://minecraft.net/terms WITH https://go.microsoft.com/fwlink/?LinkId=521839
          oci: true

      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
