name: Update README
on:
  workflow_dispatch:
  push:
    paths:
      - "property-definitions.json"
jobs:
  update:
    name: Update README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Just do it
        run: |
          echo "" > TEST_README.md
          echo "| Property | ENV | ARGS |" >> TEST_README.md
          echo "| -------- | --- | ---- |" >> TEST_README.md

          for c in `cat property-definitions.json | jq -r 'keys[]'`
          do
              echo "| ${c} | | |" >> TEST_README.md
          done

      - name: Try commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Updated readme"
